name: push-image
on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push image to Github Container Registery
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TEST_ACTION_REPO_SECRET}}

      - name: Generate Tag
        id: tag-prep
        run: |
          sha=${GITHUB_SHA::7}
          ts=$(date +'%Y.%m.%d')
          echo "::set-output name=BUILD_ID::${ts}.${sha}" 
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/pouria-yvr/hello_world:${{ steps.tag-prep.outputs.BUILD_ID }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}