name: Pull Request Workflow
on: pull_request

jobs:
  run_tests:
    name: Run tests after pull request is created or updated
    runs-on: ubuntu-latest 

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build the image
        run: docker-compose build --compress --force-rm

      - name: Run the container
        run: docker-compose up -d

      - name: Run the tests
        run: python -m unittest tests/test.py
          